module.exports = {
    USER_LOGIN: "USER_LOGIN",
    FEED_UPDATE: "FEED_UPDATE",
    AOI_UPDATE: "AOI_UPDATE",
    CENTER_UPDATE: "CENTER_UPDATE",
    EXECUTE_SEARCH: "EXECUTE_SEARCH",
    RECEIVE_SEARCH_RESULTS: "RECEIVE_SEARCH_RESULTS"
};